"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

SECRET_KEY = config('SECRET_KEY')

DEBUG = config(
    'DEBUG',
    default=False,
    cast=bool
)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS'
).split(',')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/




# Application definition

INSTALLED_APPS = [
    # daphne en tête pour fournir le serveur ASGI (runserver)
    'daphne',
    'channels',

    'django_celery_beat',

    'applications.aide',
    'applications.visiteurs',
    'applications.caisse',
    'applications.discipline',
    'applications.validation',
    'applications.conges',
    'applications.evenements',
    'applications.galerie',
    'applications.notes',
    'applications.planification',
    'applications.prestations',
    'applications.tableau_bord',
    'applications.documents',
    'applications.stocks',
    'applications.contrats',
    'applications.notifications',
    'applications.reservations',
    'applications.audiences',
    'applications.salles',
    'applications.filiales',
    'applications.utilisateurs',
    'applications.journalisation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tierces parties
    'rest_framework',
    'django_filters',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Channel layer pour les WebSockets.
# - InMemory : OK uniquement si HTTP et WebSocket sont dans le MÊME processus
#   (ex. `manage.py runserver`).
# - Redis : nécessaire dès qu'on sépare l'API (WSGI/waitress) et le WebSocket
#   (daphne) en 2 processus, car la couche doit être partagée entre eux.
# Active automatiquement Redis si REDIS_URL est défini (ex. redis://127.0.0.1:6379/0).
REDIS_URL = config("REDIS_URL", default="")

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            # Variante pub/sub : abonnement persistant, robuste pour les
            # connexions WebSocket longue durée (pas de timeout de lecture).
            "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',

        'NAME': config('DB_NAME'),

        'USER': config('DB_USER'),

        'PASSWORD': config('DB_PASSWORD'),

        'HOST': config('DB_HOST'),

        'PORT': config('DB_PORT'),

        # Connexions persistantes : évite de rouvrir une connexion (handshake
        # SSL + latence réseau vers Supabase eu-west-1) à CHAQUE requête.
        # Sûr avec le pooler en mode session (port 5432).
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=600, cast=int),
        'CONN_HEALTH_CHECKS': True,

        # SSL requis pour Supabase, pas nécessaire en local
        'OPTIONS': {
            'sslmode': config('DB_SSLMODE', default='prefer'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'


TIME_ZONE = 'Africa/Lome'

USE_I18N = True

USE_TZ = True


# =====================================================================
# Celery — traitements planifiés et differes
# =====================================================================

# Sans Redis, Celery bascule sur un broker mémoire : les tâches appelées
# avec .delay() sont alors exécutées immédiatement, dans le processus
# appelant. Pratique en développement, jamais en production.
CELERY_BROKER_URL = REDIS_URL or "memory://"
CELERY_RESULT_BACKEND = REDIS_URL or "cache+memory://"
CELERY_TASK_ALWAYS_EAGER = not REDIS_URL
CELERY_TASK_EAGER_PROPAGATES = True

CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Horaires stockés en base et modifiables depuis l'admin Django.
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Un accusé de réception après exécution (et non avant) : si un worker meurt
# en plein traitement, la tâche est reprise plutôt que perdue. Les tâches
# doivent donc rester idempotentes — une acquisition de congés relancée ne
# doit pas créditer deux fois.
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Garde-fous : une tâche qui part en boucle est arrêtée plutôt que de
# monopoliser un worker.
# =====================================================================
# Conges
# =====================================================================

# Report des conges non pris, en annees. None = cumul illimite, les jours
# ne sont jamais perdus (decision OSEOR). Le Code du travail togolais
# (art. 200 a 202) n'impose qu'un report de deux ans d'accord-parties :
# mettre 2 ici pour s'aligner sur le minimum legal, et replanifier la
# tache conges.expirer_soldes.
# =====================================================================
# Caisse
# =====================================================================

# Au-dela de ce montant, une sortie de caisse releve de la direction ; en
# deca, un chef de service suffit. Evite que le demandeur ne choisisse
# l'approbateur le plus accommodant.
CAISSE_SEUIL_DIRECTION = config(
    "CAISSE_SEUIL_DIRECTION", default="100000")


CONGES_REPORT_MAX_ANNEES = config(
    "CONGES_REPORT_MAX_ANNEES", default=None,
    cast=lambda v: None if v in ("", "None", None) else int(v),
)


CELERY_TASK_SOFT_TIME_LIMIT = 300
CELERY_TASK_TIME_LIMIT = 360



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = "utilisateurs.Utilisateur"


CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
]


# =====================================================================
# API REST (Django REST Framework) + Authentification JWT
# =====================================================================

from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "config.pagination.OseorPagination",
    "PAGE_SIZE": 25,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}


# =====================================================================
# CORS (frontend Angular en dev)
# =====================================================================

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:4200,http://127.0.0.1:4200",
).split(",")

CORS_ALLOW_CREDENTIALS = True


# =====================================================================
# Email (console en dev — affiche les mails dans le terminal)
# =====================================================================

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)

DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="no-reply@oseor-digitalisation.local",
)

# SMTP (prod — ex. Office 365 : smtp.office365.com:587, TLS)
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)


# =====================================================================
# Fichiers statiques collectés (prod : collectstatic + nginx/WhiteNoise)
# =====================================================================

STATIC_ROOT = BASE_DIR / "staticfiles"


# =====================================================================
# Durcissement sécurité — actif uniquement en PRODUCTION (DEBUG=False)
# =====================================================================

if not DEBUG:
    # HTTPS / cookies sécurisés
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Derrière un reverse proxy (nginx) qui termine le TLS
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # HSTS
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # En-têtes de protection
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # CORS : en prod, restreindre aux domaines déclarés (jamais '*')
    CORS_ALLOW_ALL_ORIGINS = False


# =====================================================================
# Active Directory de l'entreprise — authentification LDAP (optionnel)
# Active si LDAP_SERVER_URI est défini dans .env.
# Nécessite : pip install ldap3
# =====================================================================

LDAP_SERVER_URI = config('LDAP_SERVER_URI', default='')
LDAP_DOMAIN = config('LDAP_DOMAIN', default='')
LDAP_BASE_DN = config('LDAP_BASE_DN', default='')
LDAP_BIND_DN = config('LDAP_BIND_DN', default='')
LDAP_BIND_PASSWORD = config('LDAP_BIND_PASSWORD', default='')

if LDAP_SERVER_URI and LDAP_DOMAIN:
    # Backend LDAP en priorité, local en fallback (admin Django, comptes de test)
    AUTHENTICATION_BACKENDS = [
        'applications.utilisateurs.ldap_backend.OseorLDAPBackend',
        'django.contrib.auth.backends.ModelBackend',
    ]


# =====================================================================
# Tests : base SQLite en mémoire (rapide, sans Supabase ni Redis)
# =====================================================================

import sys  # noqa: E402

if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    }
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_BROKER_URL = "memory://"
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]