# Generated by Django 6.0.6 on 2026-09-14 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_utilisateur_date_embauche'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeConnexionSSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empreinte', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Empreinte du code')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_sso', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur authentifié')),
            ],
            options={
                'verbose_name': 'Code de connexion SSO',
                'verbose_name_plural': 'Codes de connexion SSO',
                'ordering': ['-date_creation'],
            },
        ),
    ]
